### ISSUE TITLE
Bad search result when searching for subtitles using integrated Pulsar Library

### ISSUE THREAD

**Issue by MrYaz** [mancuniancol/script.subscription.pulsar.favourites#2]
Thanks a lot @mancuniancol for the great addon!
I got it to work but still have some issues.
I cannot get the subtitle services to find the correct subs when accessing the shows via the KODI library .

When I have the Action setting in the add-on configuration set to "Link" I get search results with the string "link" in the name, See this screenshot: 
![subtitles_pulsar_through_library](https://cloud.githubusercontent.com/assets/1811963/11133933/70c0c964-8999-11e5-9680-b61b7fb3a2cf.png)

When I have set the Action setting to "Play" I get these search results instead:
![subtitles_pulsar_through_library_play](https://cloud.githubusercontent.com/assets/1811963/11134039/27751520-899a-11e5-9e71-7895b9a236a0.png)

When accessing the shows via The Favorites menu or directly using Pulsar the subtitles works perfectly. 
![subtitles_pulsar_through_pulsar](https://cloud.githubusercontent.com/assets/1811963/11134062/452b33b0-899a-11e5-9651-92753d4e2d87.png)

**Comment by mancuniancol** [comment]
It is an known issue with Pulsar. Because, the script is not official. Then, Pulsar doesn't have that part done. Unfortunately, I am not developing a Pulsar  fork for the moment.
I will close this issue, because from the script I cannot do more to solve that.  Sorry
